train_file:  ["/localhome/local-chrislin/vla/iros-2025-track4/datasets/track4-cross-modal-drone-navigation/train.json"]  
test_file: "/localhome/local-chrislin/vla/iros-2025-track4/datasets/track4-cross-modal-drone-navigation/test_24G_version.json" 
image_root: '/localhome/local-chrislin/vla/iros-2025-track4/datasets/track4-cross-modal-drone-navigation/images'

## Vision Encoder
vision_config: 'configs/config_swinB_384.json'

use_clip_vit: False
#image_res: 384
#patch_size: 16

use_swin: True
image_res: 384
patch_size: 32


## Text Encoder
use_roberta: False
text_config: 'configs/config_bert.json'  # ['configs/config_bert.json', 'configs/config_roberta.json']
text_encoder: '/localhome/local-chrislin/vla/iros-2025-track4/checkpoints/GeoText1652_model/bert'  # ['data/bert-base-uncased', 'data/roberta-base']



## Training
batch_size_train: 24
batch_size_test: 1
batch_size_test_text: 512
max_tokens: 50
embed_dim: 256
temp: 0.07
k_test: 256


## Other Settings
# optimizer: {opt: adamW, lr: 3e-6, weight_decay: 0.001, lr_mult: 2}
# schedular: {sched: linear, lr: 3e-6, epochs: 3, num_warmup_steps: 0.1}


optimizer: {opt: adamW, lr: 3e-5, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 3e-5, epochs: 1, num_warmup_steps: 0.1}
